_config.ymltitle: Max Mahmood
tagline: Yetidrums
email: yetidrumming+web@gmail.com
description: >-
  My music projects

url: "https://yetidrums.com"
author: ckm
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
future: true
markdown: kramdown
remote_theme: ItsPatrq/minimal-music-project
permalink: /:title.html
socials:
  instagram: https://www.instagram.com/__eternal.nightmare__/
# jekyll-feed
author: Max Mahmood
feed:
  icon: /assets/img/feedicon.png
  logo: /assets/img/yeti_logo.png
title: yetidrums.com
url: https://yetidrums.com

pagination:
  enabled: true
  per_page: 6
  limit: 0
  sort_field: 'date'
  sort_reverse: true

  exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - node_modules
